# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 00:56
from __future__ import unicode_literals

import os

from django.utils.baseconv import base56

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion

def create_tokens(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    for member in Member.objects.all():
        member.profile_memberpage.secret_token = base56.encode(int.from_bytes(os.urandom(16), byteorder='big'))
        member.profile_memberpage.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_auto_20180512_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberpageConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_other_members', models.CharField(choices=[('no', 'no'), ('name-only', 'name-only'), ('name-contact', 'name-contact')], default='no', max_length=12, verbose_name='Members can see other members')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberpageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_token', models.CharField(blank=True, max_length=128, null=True)),
                ('visible_consent', models.BooleanField(default=False, verbose_name='Consent: Visible to other members')),
                ('member', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_memberpage', to='members.Member')),
            ],
        ),
        migrations.RunPython(create_tokens, migrations.RunPython.noop),
    ]
